letras={}
letras[k_a]='a'
letras[k_b]='b'
letras[k_c]='c'
letras[k_d]='d'
letras[k_e]='e'
letras[k_f]='f'
letras[k_g]='g'
letras[k_h]='h'
letras[k_i]='i'
letras[k_j]='j'
letras[k_k]='k'
letras[k_l]='l'
letras[k_m]='m'
letras[k_n]='n'
letras[k_o]='o'
letras[k_p]='p'
letras[k_q]='q'
letras[k_r]='r'
letras[k_s]='s'
letras[k_t]='t'
letras[k_u]='u'
letras[k_v]='v'
letras[k_w]='w'
letras[k_x]='x'
letras[k_y]='y'
letras[k_z]='z'
letras[k_A]='A'
letras[k_B]='B'
letras[k_C]='C'
letras[k_D]='D'
letras[k_E]='E'
letras[k_F]='F'
letras[k_G]='G'
letras[k_H]='H'
letras[k_I]='I'
letras[k_J]='J'
letras[k_K]='K'
letras[k_L]='L'
letras[k_M]='M'
letras[k_N]='N'
letras[k_O]='O'
letras[k_P]='P'
letras[k_Q]='Q'
letras[k_R]='R'
letras[k_S]='S'
letras[k_T]='T'
letras[k_U]='U'
letras[k_V]='V'
letras[k_W]='W'
letras[k_X]='X'
letras[k_Y]='Y'
letras[k_Z]='Z'


if event.type == pygame.KEYDOWN:
    if event.key in letras:
        letra=letras[event.key]
        nome+=letra
                        
                        


